US026 - Add branding to the product
lexseaton/team1-ui pull request #4
Opened 2024-07-23 11:13 UTC by Brigid481

Adding Branding to homepage

2024-07-23 11:29 UTC, dylanlaffin approved these changes, later dismissed
from my experience with css everything looks gook.

2024-07-23 12:38 UTC, RaggedyRach commented
Hi, maybe remove some spacing and tidy up the unused files. The images and the stylesheet. thx :)

2024-07-23 12:43 UTC, RaggedyRach approved these changes
spaces and redundant files moved. Looks good to me :)

2024-07-24 07:53 UTC, shaunganley requested changes

2024-07-24 07:53 UTC, shaunganley commented on views/homepage.html
> +<style>
move this section to a css file and import above

2024-07-24 07:53 UTC, shaunganley commented on views/homepage.html
> +    <footer class="footer">
move this section to a footer.html file and import it here. this way we can reuse on other pages

2024-07-24 07:53 UTC, shaunganley commented on views/homepage.html
> +    <div class="nav">
move this section to a heading.html file and import. that way we can reuse on other pages

2024-07-24 14:58 UTC, shaunganley approved these changes

2024-07-24 15:03 UTC, merged