001 view job roles frontend
lexseaton/team1-ui pull request #7
Opened 2024-07-24 08:22 UTC by hannahmorgan24

2024-07-24 10:47 UTC, RaggedyRach commented on src/controllers/JobRoleController.ts
Hi Hannah, I think we may want this in a try catch. 
![image](https://github.com/user-attachments/assets/c49033ed-bf32-4166-ae74-32d3f772cf9a)

2024-07-24 10:51 UTC, RaggedyRach reviewed
One possible change a try catch in the controller. 
Not sure if linting on front end will want spaces at end of each file like the back end. I will try to get it on the UI build so we can check it

2024-07-24 10:55 UTC, RaggedyRach commented on views/jobRoleList.html
oh and maybe change this to Open Job Roles List

2024-07-24 13:44 UTC, shaunganley requested changes

2024-07-24 13:44 UTC, shaunganley commented on src/controllers/JobRoleController.ts
agreed

2024-07-24 13:44 UTC, shaunganley commented on src/models/Band.ts
> +export enum Band {
don't want to hardcode bands, keep this as a string

2024-07-24 13:44 UTC, shaunganley commented on src/models/Capability.ts
> +export enum Capability {
don't want to hardcode capability, keep this as a string

2024-07-24 13:44 UTC, shaunganley commented on test/unit/services/JobRoleServiceTests.ts
> +      it('should return job roles from response', async () => {
add a unit test for 500 error from axios

2024-07-24 13:44 UTC, shaunganley commented on views/jobRoleList.html
> +        {% for openJobRole in openJobRoles | sort(attribute='jobRoleID') %}
jobRoleID doesn't exist in your model

2024-07-25 10:26 UTC, shaunganley approved these changes

2024-07-25 11:12 UTC, RaggedyRach approved these changes

2024-07-25 12:35 UTC, Brigid481 approved these changes
looks good Rachael

2024-07-26 08:21 UTC, RaggedyRach approved these changes

2024-07-26 08:34 UTC, merged